In [ ]:
#K nearest neighbour(KNN) #ASSIGNMENT

In [2]:
import pandas as pd 

In [41]:
df=pd.read_csv("C:/Users/lenovo/Desktop/datasets/diabetes2.csv")
df.head(10)

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6      148             72             35        0  33.6   
1            1       85             66             29        0  26.6   
2            8      183             64              0        0  23.3   
3            1       89             66             23       94  28.1   
4            0      137             40             35      168  43.1   
5            5      116             74              0        0  25.6   
6            3       78             50             32       88  31.0   
7           10      115              0              0        0  35.3   
8            2      197             70             45      543  30.5   
9            8      125             96              0        0   0.0   

   DiabetesPedigreeFunction  Age  Outcome  
0                     0.627   50        1  
1                     0.351   31        0  
2                     0.672   32        1  
3                     0.167   21        0  
4                     2.288   33        1  
5                     0.201   30        0  
6                     0.248   26        1  
7                     0.134   29        0  
8                     0.158   53        1  
9                     0.232   54        1

In [43]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 768 entries, 0 to 767
Data columns (total 9 columns):
 #   Column                    Non-Null Count  Dtype  
---  ------                    --------------  -----  
 0   Pregnancies               768 non-null    int64  
 1   Glucose                   768 non-null    int64  
 2   BloodPressure             768 non-null    int64  
 3   SkinThickness             768 non-null    int64  
 4   Insulin                   768 non-null    int64  
 5   BMI                       768 non-null    float64
 6   DiabetesPedigreeFunction  768 non-null    float64
 7   Age                       768 non-null    int64  
 8   Outcome                   768 non-null    int64  
dtypes: float64(2), int64(7)
memory usage: 54.1 KB


In [45]:
x=df[["Pregnancies","Glucose","BMI","Age"]]
y=df[["Outcome"]]

In [48]:
x.head(10)

Pregnancies  Glucose   BMI  Age
0            6      148  33.6   50
1            1       85  26.6   31
2            8      183  23.3   32
3            1       89  28.1   21
4            0      137  43.1   33
5            5      116  25.6   30
6            3       78  31.0   26
7           10      115  35.3   29
8            2      197  30.5   53
9            8      125   0.0   54

In [49]:
y.head(10)

Outcome
0        1
1        0
2        1
3        0
4        1
5        0
6        1
7        0
8        1
9        1

In [50]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3,random_state=0)
y_test

Outcome
661        1
122        0
113        0
14         1
529        0
..       ...
165        1
188        1
334        0
758        0
34         0

[231 rows x 1 columns]

In [51]:
x_train

Pregnancies  Glucose   BMI  Age
580            0      151  42.1   21
418            1       83  18.2   27
764            2      122  36.8   27
363            4      146  38.5   67
757            0      123  36.3   52
..           ...      ...   ...  ...
763           10      101  32.9   63
192            7      159  30.4   36
629            4       94  24.7   21
559           11       85  30.1   35
684            5      136   0.0   69

[537 rows x 4 columns]

In [52]:
x_test

Pregnancies  Glucose   BMI  Age
661            1      199  42.9   22
122            2      107  33.6   23
113            4       76  34.0   25
14             5      166  25.8   51
529            0      111  24.6   31
..           ...      ...   ...  ...
165            6      104  29.9   41
188            8      109  27.9   31
334            1       95  23.9   22
758            1      106  37.5   26
34            10      122  27.6   45

[231 rows x 4 columns]

In [56]:
from sklearn.linear_model import LogisticRegression
logmodel = LogisticRegression()

In [57]:
logmodel.fit(x_train,y_train)

D:\New folder (4)\lib\site-packages\sklearn\utils\validation.py:1143: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


LogisticRegression()

In [58]:
y_pred=logmodel.predict(x_test)
y_pred

array([1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1,
       1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1,
       1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0], dtype=int64)

In [59]:
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score

results=confusion_matrix(y_test,y_pred)
print('confusion matrix')
print(results)
print('Accuracy score:',accuracy_score(y_test,y_pred))

confusion matrix
[[139  18]
 [ 38  36]]
Accuracy score: 0.7575757575757576


In [62]:
import numpy as np
k=np.array([[1,199,42.9,22]])
k

array([[  1. , 199. ,  42.9,  22. ]])

In [63]:
pred=logmodel.predict(k)
pred

D:\New folder (4)\lib\site-packages\sklearn\base.py:420: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(


array([1], dtype=int64)